export const ACTIVITY_EVENT_TYPES = [
  "SUCCESS",
  "FAILED",
  "LOCKED",
  "AUTH_LOGIN_SUCCESS",
  "AUTH_LOGIN_FAILED",
  "AUTH_LOCKED",
  "AUTH_LOGOUT",
  "AUTH_SIGNUP",
  "AUTH_PASSWORD_RESET_REQUESTED",
  "NOTE_CREATED",
  "NOTE_UPDATED",
  "NOTE_PINNED",
  "NOTE_UNPINNED",
  "NOTE_ARCHIVED",
  "NOTE_UNARCHIVED",
  "NOTE_TRASHED",
  "NOTE_DELETED_PERMANENTLY",
  "PROFILE_UPDATED",
  "PASSWORD_CHANGED",
] as const;

export type ActivityEventType = (typeof ACTIVITY_EVENT_TYPES)[number];
